### ISSUE TITLE
Confused by Read Me information and the updated other item

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Script-LoadoutController#4]
OK as I am reading through the file here I see that it shows "Not needed anymore" in the loadouts folder description. Is that referring to the randomizer or what? What about the following?.....
> [] execVM "loadouts\createLoadout.sqf";
Does it have to go into my init file now where I am running the briefing script and the VCOM AI init on mission start? 

I am getting utterly confused by all this now.

**Comment by Jmaster9999** [comment]
Oh... The not needed anymore was from a previous commit where I removed the randomizer. Since it was the last change in that folder the commit is displayed next to it.  The only thing you need to do is copy the loadout folder into the root of your missionfile, then add `nul = [this,"loadoutName"] execVM "loadouts\createLoadout.sqf";` to your unit init boxes in the editor. You don't need to add anything to the init.sqf or do anything file related except for adding the loadouts into the loadout folder.
