### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Script-LoadoutController#5]
What is this SHG_Loadout aspect referring to?

_unit setVariable ["SHG_Loadout",_loadoutFormat,false];

**Comment by Jmaster9999** [comment]
SHG_loadout has been renamed to TF_RED_Loadout, good catch. The variable stores the assigned loadout information on the player. When the player respawns a event handler runs and retrieves the loadout information from the player's body; The loadout information is then used to spawn the appropriate loadout on the new player character. 

While I could have used a global client variable, I avoid using global variables wherever possible since it's good practice because excessive use of global variables increase the change of variable name conflicts (When two different pieces of code try to use the same variable).
